service: dynamodb-scheduled-backup

useDotenv: true

frameworkVersion: '3'

package:
  patterns:
    # Includes
    - 'dist/**.js'
    # Excludes
    - '!./**.md'
    - '!.git/**'
    - '!dist/tsconfig.build.tsbuildinfo'
    - '!src/**'
    - '!.eslintrc.js'
    - '!./tsconfig*.json'
    - '!.github/**'
    - '!LICENSE'

provider:
  name: aws
  architecture: arm64
  runtime: nodejs14.x
  versionFunctions: false
  region: eu-west-1
  memorySize: 256
  logRetentionInDays: 5
  deploymentBucket:
    name: ${param:S3_BUCKET}
    blockPublicAccess: true
    maxPreviousDeploymentArtifacts: 3
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - 'dynamodb:ListTables'
            - 'dynamodb:CreateBackup'
            - 'dynamodb:ListBackups'
            - 'dynamodb:DeleteBackup'
          Resource:
            - '*'

functions:
  create-backup:
    handler: dist/create-backup/index.handler
    description: Creates backup of DynamoDB Tables
    timeout: 5
    environment:
      REGION: eu-west-1    
    events:
      # Every Sunday at 12 noon
      - schedule: cron(0 12 ? * SUN *)
  delete-backup:
    handler: dist/delete-backup/index.handler
    description: Delete backups of tables which are older than a certain threshold
    timeout: 5
    environment:
      REGION: eu-west-1
      DAYS_TO_RETAIN: 7
    events:
      # Every Sunday at 12 noon
      - schedule: cron(0 12 ? * SUN *)